### PR TITLE
Next.js init

### LINKED ISSUE #3: tech stack discussion
svelte bad

### PR DESCRIPTION
**Pull request by Weredime**
Resolves #3

# Changes
Introducing Next.js instead of SvelteKit

Btw guys feel free to push to this branch, but test it first

### CODE REVIEW

**Comment by kccuber-scratch** [comment]
delete vercel.svg? seems like that has no use

**Comment by Weredime** [comment]
See #8

**Review by kccuber-scratch — APPROVED** [review]

**Comment by Chiroyce1** [comment]
image

bad?11?! /s

**Comment by Looky1173** [comment]
> image
> 
> bad?11?! /s

Imagine the chances of this happening... Wow

**Pull request merged**
