### PR TITLE
add SCSS (draft)

### PR DESCRIPTION
**Pull request by ScolderCreations**
I think we should use Sass as it’s probably going to make stuff a lot easier. CSS variables are cool :P

I’ve made a general file so far, but I think we should have more CSS.

### CODE REVIEW

**Comment by Weredime** [comment]
WWW is going to be split into two parts: www and api. www will be a sveltekit app and api is a fastify rest api. I have most of the things on my machine but I didn't have time to post it - I'll do it tomorrow

**Comment by ScolderCreations** [comment]
> WWW is going to be split into two parts: www and api. www will be a sveltekit app and api is a fastify rest api. I have most of the things on my machine but I didn't have time to post it - I'll do it in the next hour
> 
> And I'm pretty sure scss is on sveltekit by default

Ok, let me know if this PR is unnecessary or conflicting.

**Comment by Weredime** [comment]
> > WWW is going to be split into two parts: www and api. www will be a sveltekit app and api is a fastify rest api. I have most of the things on my machine but I didn't have time to post it - I'll do it in the next hour
> > And I'm pretty sure scss is on sveltekit by default
> 
> Ok, let me know if this PR is unnecessary or conflicting.

Yeah - its conflicting - sorry. I'll merge the css for you in, but I sadly can't merge this PR

**Comment by Weredime** [comment]
Done in https://github.com/screech-org/www/commit/5570859142107a76f33eb8586518eb5b44142455

**Pull request closed without merging**
